/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : hid1.c
**     Project     : hid_loader_k22f
**     Processor   : MK22FN512VLH12
**     Component   : fsl_usb_device_hid_class
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-06-07, 11:51, # CodeGen: 10
**     Abstract    :
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     All Rights Reserved.
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file hid1.c
** @version 01.00
** @brief
**
*/
/*!
**  @addtogroup hid1_module hid1 module documentation
**  @{
*/

/* MODULE hid1. */

#include "hid1_hid.h"
#include "hid1.h"

/* USB HID device class handle */
hid_handle_t hid1_HidHandle;


/* USB HID class configuration structure */
extern usb_desc_request_notify_struct_t usbDsc1_desc_callback;
hid_config_struct_t hid1_HidConfigStructure = {
  .hid_application_callback.callback = &hid1_application_callback,
  .hid_application_callback.arg = (void *)NULL,
  .vendor_req_callback.callback = NULL,
  .vendor_req_callback.arg = (void *)NULL,
  .class_specific_callback.callback = &hid1_class_specific_callback,
  .class_specific_callback.arg = (void *)NULL,
  .desc_callback_ptr = &usbDsc1_desc_callback
};

const uint8_t hid1_ReportDescriptor[] = {
//0x06, 0x00, 0xff,           // USAGE_PAGE (Generic Desktop)
0x05, 0x00,                 // USAGE_PAGE (Undefined)
//0x09, 0x01,                 // USAGE (Vendor Usage 1)
0x09, 0x00,                 // USAGE (Undefined)
0xa1, 0x01,                 // COLLECTION (Application)
0x15, 0x00,                 // LOGICAL_MINIMUM (0)
0x26, 0xff, 0x00,           // LOGICAL_MAXIMUM (255)
0x75, 0x08,                 // REPORT_SIZE (8)

0x85, HID_REQUEST_VERSIONS, // REPORT_ID (HID_REQUEST_VERSIONS)
0x95, 0x0C,                 // REPORT_COUNT (12)
0x09, 0x00,                 // USAGE (Undefined)
0xb2, 0x23, 0x01,           // FEATURE (Const,Var,Abs,NPrf,Buf)

0x85, HID_OUTPUT_BLOCK,     // REPORT_ID (HID_OUTPUT_BLOCK)
0x96, 0x03, 0x04,           // REPORT_COUNT (1027)
0x09, 0x00,                 // USAGE (Undefined)
0x92, 0x06, 0x01,           // Output(Data, Variable, Relative, No Wrap, Linear, Preferred State, No Null Position, Non-volatile, Buffered Bytes) */

0xc0                        // END_COLLECTION
};


/* END hid1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
