/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : usbDsc1.h
**     Project     : hid_loader_k22f
**     Processor   : MK22FN512VLH12
**     Component   : fsl_usb_descriptors
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-06-07, 11:51, # CodeGen: 10
**     Abstract    :
**          This component encapsulates the Universal Serial Bus (USB)
**          module in the device mode according to specification 2.0.
**          It allows design variable configurations, interfaces and endpoints.
**     Settings    :
**          Component name                                 : usbDsc1
**          Lower level component link                     : usbFmw1
**          Generated code common settings                 :
**            Mark all descriptors as const                : yes
**          Composite device                               : no
**          Class setting                                  :
**            AUDIO class support                          : no
**            CDC class support                            : no
**            HID class support                            : yes
**            MSD class support                            : no
**          Supported languages                            : 1
**            Language 0                                   : 0x0409 English (United States)
**          External power source                          : yes
**          Common device settings                         :
**            USB revision                                 : USB 2.0
**            Vendor ID                                    : 0x7722
**            Product ID                                   : 0x1200
**            Device release number                        : 01.00
**            Manufacturer description                     : Enabled
**              Language list                              : 1
**                Language 0                               : hologram.io
**            Product description                          : Enabled
**              Language list                              : 1
**                Language 0                               : Dash Loader
**            Device's serial number                       : Enabled
**              Descriptor index                           : 3
**              Language list                              : 1
**                Language 0                               : 
**            Device speed                                 : Full speed
**              Device description                         :
**                Class code                               : 0x00 Class information at interface level
**                Subclass code                            : 0
**                Protocol code                            : 0
**                EP0 settings                             :
**                  Max packet size                        : 64
**                Configuration list                       : 1
**                  Configuration 1                        :
**                    Configuration name                   : usbDsc1_Full_Speed_Configuration_1
**                    Total length                         : 34
**                    Configuration description            : Enabled
**                      Language list                      : 1
**                        Language 0                       : Configuration 1
**                    Power characteristics                : self powered
**                    Maximum power consumption            : 0 mA
**                    Remote wake-up                       : yes
**                    Class list                           : 1
**                      Class 0                            :
**                        Class component name             : hid1
**                        Class user name                  :
**                        Implementation specific settings : SDK
**                          SDK specific settings          :
**                            SDK callbacks                :
**                              USB_Desc_Get_Descriptor callback name:
**                              USB_Desc_Get_Entity callback name:
**                            Class config structure       :
**                              Application callback       :
**                                Callback name            : hid1_application_callback
**                                Callback parametr        : NULL
**                                External declaration of parameter:
**                              Class specific callback    :
**                                Callback name            : hid1_class_specific_callback
**                                Callback parametr        : NULL
**                                External declaration of parameter:
**                              Vendor request callback    :
**                                Callback name            : NULL
**                                Callback parametr        : NULL
**                                External declaration of parameter:
**                        Interface list                   : 1
**                          Interface 0                    :
**                            Alternate setting list       : 1
**                              Alternate setting 0        :
**                                Interface user name      :
**                                Default request handler name:
**                                Class code               : 0x03 HID
**                                Subclass code            : 0x00 No Subclass
**                                Protocol code            : 0x00 None
**                                Alternate setting description: Disabled
**                                Class descriptors        : 0x03 HID
**                                  HID descriptor         :
**                                    HID Class specification release number: 1.11
**                                    Country code         : 0x00 Not Supported
**                                    Class descriptor list: 1
**                                      HID class descriptor 0:
**                                        Descriptor type  : HID_REPORT
**                                        Descriptor size  : 22
**                                        Descriptor name  : hid1_ReportDescriptor
**                                Pipe list                : 1
**                                  Pipe 0                 : Interrupt IN
**                                    Pipe user name       : hid1_PipeIn
**                                    Default request handler name:
**                                    Endpoint number      : 1
**                                    Maximum packet size  : 8
**                                    Polling interval     : 1 ms
**                                    ZLT                  : yes
**          SDK settings                                   :
**            Class drivers configuration                  :
**              CDC driver configuration                   : Disabled
**              HID class driver configuration             : Enabled
**                Max. human interface device number       : 1
**                Max. class endpoint number               : 1
**                Data transfer queuing                    : Disabled
**              MSD class driver configuration             : Disabled
**              Composite driver configuration             : Disabled
**            Initialization composite device              : Disabled
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     All Rights Reserved.
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file usbDsc1.h
** @version 01.00
** @brief
**          This component encapsulates the Universal Serial Bus (USB)
**          module in the device mode according to specification 2.0.
**          It allows design variable configurations, interfaces and endpoints.
*/
/*!
**  @addtogroup usbDsc1_module usbDsc1 module documentation
**  @{
*/

#ifndef __usbDsc1_H
#define __usbDsc1_H

/* MODULE usbDsc1. */
/* Include inherited components */
#include "usbFmw1.h"
#include "Cpu.h"

/* Descriptors codes */
#define USB_DEVICE_DESCRIPTOR                       (0x01)
#define USB_CONFIGURATION_DESCRIPTOR                (0x02)
#define USB_STRING_DESCRIPTOR                       (0x03)
#define USB_INTERFACE_DESCRIPTOR                    (0x04)
#define USB_ENDPOINT_DESCRIPTOR                     (0x05)
#define USB_DEVICE_QUALIFIER_DESCRIPTOR             (0x06)
#define USB_OTHER_SPEED_CONFIGURATION_DESCRIPTOR    (0x07)
#define USB_AUDIO_DESCRIPTOR                        (0x25)
#define USB_REPORT_DESCRIPTOR                       (0x22)

#define USB_HID_DESCRIPTOR                          (0x21)
#define USB_HID_REPORT_DESCRIPTOR                   (0x22)
#define USB_HID_PHYSICAL_DESCRIPTOR                 (0x23)

#define PRODUCT_STRING "Dash"
#define PRODUCT_STRING_SIZE 4

#define ROLE_STRING "Updater"
#define ROLE_STRING_SIZE 7

void load_usb_strings(void);

/* END usbDsc1. */
#endif
/* ifndef __usbDsc1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
